<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 26/07/2018
 * Time: 6:20 PM
 */


require_once ("weather\controllers\db_connect.php");
class Model_Registration extends Model{

//    private $full_name;
//    private $email;
//    private $password;
//    private $gender;
//    private $birthdate;
//
//
    private $user_data;

    function __construct($fullName, $email, $password, $gender=null, $birthdate=null){

            $this->user_data[0] = $fullName;
            $this->user_data[1] = $email;
            $this->user_data[2] = $password;
            if($gender){
                $this->user_data[3] = $gender;
            }
            if ($birthdate){
                $this->user_data[4] = $birthdate;
            }
    }

    public function get_data()
    {
        return $this->user_data;
        #parent::get_gata(); // TODO: Change the autogenerated stub
    }


}