<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 26/07/2018
 * Time: 6:20 PM
 */



class scsc extends Model{

//    private $full_name;
//    private $email;
//    private $password;
//    private $gender;
//    private $birthdate;
//
//
    private $user_data;

    function __construct($fullName, $email, $password, $gender=null, $birthdate=null){

            $this->user_data["full_name"] = $fullName;
            $this->user_data["email"] = $email;
            $this->user_data["password"] = $password;
            if($gender){
                $this->user_data["gender"] = $gender;
            }
            if ($birthdate){
                $this->user_data["birthdate"] = $birthdate;
            }
    }

    public function get_data()
    {
        return $this->user_data;
        #parent::get_gata(); // TODO: Change the autogenerated stub
    }


}